.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "HASHBASE" "1" "July 2014" "" ""
.
.SH "NAME"
\fBhashbase\fR \- flexible hackable\-storage
.
.SH "SYNOPSIS"
\fBhashbase\fR
.
.br
\fBhashbase\fR [\fIoptions\fR\.\.\.]
.
.br
\fBhashbase\fR \fB\-d\fR|\fB\-\-daemonize\fR
.
.br
\fBhashbase\fR \fB\-p\fR \fIport\fR
.
.br
.
.SH "DESCRIPTION"
It\'s a fast, efficient on\-disk/in\-memory database with many different kind of data structure\.
.
.SH "OPTIONS"
These options control whether output is written to file(s), standard output, or directly to a man pager\.
.
.TP
\fB\-d\fR, \fB\-\-daemonize\fR
Run in the background\.
.
.TP
\fB\-p\fR \fIport\fR, \fB\-\-port\fR \fIport\fR
Set port for server\.
.
.TP
\fB\-v\fR, \fB\-\-version\fR
Show hashbase version and exit\.
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Show help and exit\.
.
.SH "EXAMPLES"
Serve TCP server at <tcp://localhost:1207/> as daemon:
.
.IP "" 4
.
.nf

$ hashbase \-p 1207 \-d
.
.fi
.
.IP "" 0
.
.SH "BUGS"
\fBHashbase\fR is written in ANSI C and depends on autoconf and extension libraries that are non\-trivial to install on some systems\. A more portable version of this program would be welcome\.
.
.SH "COPYRIGHT"
Hashbase is Copyright (C) 2014 Maciej A\. Czyzewski
.
.SH "SEE ALSO"
man(1), manpages(5)
